In [4]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
responce =stats.ks_2samp(sample1, sample2)

In [6]:
sample1

array([0.660144  , 0.58077054, 0.28793392, 0.18919269, 0.72662601,
       0.66193648, 0.17389936, 0.78177471, 0.4130251 , 0.14668786,
       0.47547422, 0.00211626, 0.40612547, 0.2856108 , 0.29535476,
       0.15225629, 0.19623003, 0.32838212, 0.91823314, 0.37571954,
       0.43880216, 0.212985  , 0.99021917, 0.33373496, 0.071353  ,
       0.10363608, 0.29022576, 0.72997559, 0.29865201, 0.55911869,
       0.11641887, 0.29903508, 0.05912436, 0.68740626, 0.96842618,
       0.86349006, 0.97359696, 0.73777705, 0.08922126, 0.7851612 ,
       0.83091565, 0.93228351, 0.41585048, 0.19537346, 0.30589764,
       0.98658141, 0.45110985, 0.75882601, 0.67794224, 0.84703502,
       0.56166764, 0.43793212, 0.08291828, 0.73709789, 0.82558901,
       0.30745015, 0.23517364, 0.52940178, 0.10668755, 0.50495372,
       0.06249761, 0.98882797, 0.75162515, 0.66120457, 0.33439578,
       0.748477  , 0.51268954, 0.23852415, 0.90312176, 0.65401258,
       0.91855774, 0.54329086, 0.32718419, 0.05762699, 0.35755

In [7]:
sample2

array([-0.13709925,  2.46152418, -0.71052875, -0.50185081,  0.02081619,
        0.8881608 , -0.16634335, -1.28975221,  1.87894348, -1.35295265,
        0.34674099, -1.54122236,  0.59142523, -0.89339877,  1.11799998,
        0.36945641, -0.00346453,  0.49811179, -0.69744736, -0.07830443,
        0.41160554,  0.16462472,  0.62814859,  0.57199504,  0.94484381,
        0.40480765, -0.06491163,  0.23835391, -0.02300101,  0.47027188,
       -0.05620528, -0.84882986, -0.22277696, -0.72755223, -1.29875607,
        0.58601146,  0.33146795, -1.35104798, -0.76460861, -0.1923194 ,
       -0.16097422, -0.55443408,  0.49656317,  0.69854802, -0.50157199,
        0.17272944, -0.14197482, -0.2148148 ,  1.2616045 , -0.25785458,
        1.84626731,  0.36894838,  0.13450287,  0.69720139, -0.99308359,
       -0.04634398, -0.00488053, -0.21432673,  0.31099407, -0.20543029,
        0.41543792, -1.85967547, -0.93556185,  0.65602933,  0.55620928,
       -0.09175809,  0.29719761, -1.99145964,  0.55959265, -0.86

In [5]:
responce

KstestResult(statistic=np.float64(0.5), pvalue=np.float64(1.8772727817852512e-12), statistic_location=np.float64(-0.003464527394669418), statistic_sign=np.int8(-1))

In [9]:
responce.pvalue

np.float64(1.8772727817852512e-12)

In [14]:
round(responce.pvalue,10)

np.float64(0.0)

In [15]:
round(responce.pvalue,16)

np.float64(1.8773e-12)

In [ ]:
# Anomaly in dataset
# 1. High Null value
# 2.Missung 
# 3. outlier
# 4. For Categorical :
Gender--> Male,Female,Other


In [14]:
import os
print(os.getcwd())


e:\ABBC\Aps_Fault_Detection\notebook


In [15]:
import pandas as pd

In [33]:
l1= [1,2,3,4]
l2 =[4,5,6,7,8,9]

for l1_val,l2_val in zip(l1,l2):
    print(l1_val,l2_val)

1 4
2 5
3 6
4 7


In [40]:
df = pd.read_csv(r"E:\ABBC\Aps_Fault_Detection\artifact\07052025__203714\data_ingestion\dataset\train.csv")

In [ ]:
null_report=df.isnull().sum()/df.shape[0]


In [ ]:
null_report[null_report>0.3].index

In [54]:
df.iloc[:,[0]]

class
0       neg
1       neg
2       neg
3       neg
4       neg
...     ...
28945   neg
28946   neg
28947   neg
28948   neg
28949   neg

[28950 rows x 1 columns]

In [57]:
len(df.iloc[:,[0]].drop("class",axis=1).columns)

0

In [25]:
df.isnull().sum()

class         0
aa_000        0
ab_000    22358
ac_000     1723
ad_000     7413
          ...  
ee_007      305
ee_008      305
ee_009      305
ef_000     1398
eg_000     1397
Length: 171, dtype: int64

In [ ]:
df.isnull().sum()/df.shape[0]# avobe 30% null drop

class     0.000000
aa_000    0.000000
ab_000    0.772297
ac_000    0.059516
ad_000    0.256062
            ...   
ee_007    0.010535
ee_008    0.010535
ee_009    0.010535
ef_000    0.048290
eg_000    0.048256
Length: 171, dtype: float64

In [27]:
(df.isnull().sum()/df.shape[0]).values

array([0.        , 0.        , 0.77229706, 0.05951641, 0.25606218,
       0.04431779, 0.04431779, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01098446, 0.01074266, 0.01074266,
       0.0784456 , 0.01088083, 0.01074266, 0.01088083, 0.00974093,
       0.01088083, 0.00974093, 0.04825561, 0.01074266, 0.01074266,
       0.01074266, 0.04435233, 0.04435233, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01098446, 0.04829016,
       0.04829016, 0.04438687, 0.04431779, 0.01088083, 0.01088083,
       0.00974093, 0.00974093, 0.37920553, 0.44770294, 0.65274

In [28]:
(df.isnull().sum()/df.shape[0]).values.__len__()

171

In [30]:
(df.isnull().sum()/df.shape[0]).index

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [34]:
drop_column_name=[]
for column_names, missing_percentage in  zip((df.isnull().sum()/df.shape[0]).index, (df.isnull().sum()/df.shape[0]).values):
    print(column_names,missing_percentage*100)
    if missing_percentage >0.3:
        drop_column_name.append(column_names)

class 0.0
aa_000 0.0
ab_000 77.22970639032816
ac_000 5.951640759930915
ad_000 25.606217616580313
ae_000 4.431778929188256
af_000 4.431778929188256
ag_000 1.0535405872193437
ag_001 1.0535405872193437
ag_002 1.0535405872193437
ag_003 1.0535405872193437
ag_004 1.0535405872193437
ag_005 1.0535405872193437
ag_006 1.0535405872193437
ag_007 1.0535405872193437
ag_008 1.0535405872193437
ag_009 1.0535405872193437
ah_000 1.0984455958549224
ai_000 1.07426597582038
aj_000 1.07426597582038
ak_000 7.844559585492227
al_000 1.0880829015544042
am_0 1.07426597582038
an_000 1.0880829015544042
ao_000 0.9740932642487047
ap_000 1.0880829015544042
aq_000 0.9740932642487047
ar_000 4.825561312607944
as_000 1.07426597582038
at_000 1.07426597582038
au_000 1.07426597582038
av_000 4.435233160621762
ax_000 4.435233160621762
ay_000 1.0535405872193437
ay_001 1.0535405872193437
ay_002 1.0535405872193437
ay_003 1.0535405872193437
ay_004 1.0535405872193437
ay_005 1.0535405872193437
ay_006 1.0535405872193437
ay_007 1.0535

In [39]:
drop_column_name

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [50]:
null_report[null_report>0.3]

ab_000    0.772297
bk_000    0.379206
bl_000    0.447703
bm_000    0.652746
bn_000    0.725250
bo_000    0.762383
bp_000    0.785009
bq_000    0.802073
br_000    0.810743
cr_000    0.772297
dtype: float64

In [51]:
null_report[null_report>0.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [ ]:
import pandas, numpy, seaborn, matplotlib, sklearn, catboost, xgboost, dill, flask,gunicorn

print("pandas:", pandas.__version__)
print("numpy:", numpy.__version__)
print("seaborn:", seaborn.__version__)
print("matplotlib:", matplotlib.__version__)
print("scikit-learn:", sklearn.__version__)
print("catboost:", catboost.__version__)
print("xgboost:", xgboost.__version__)
print("dill:", dill.__version__)
print("Flask:", flask.__version__)
print("gunicorn:", gunicorn.__version__)

In [10]:
!pip install pymongo
!pip install pandas
!pip install PyYAML
!pip install dill
!pip install dnspython
!pip install fastapi
!pip install httptools
!pip install imblearn
!pip install mypy-boto3-s3
!pip install pip-chill
!pip install python-dotenv


In [12]:
import pymongo,pandas, PyYAML,dill,dnspython,fastapi,httptools,imblearn,mypyboto3s3,pipchill,pymongo,pythondotenv,typess3transfer,uvicorn,watchfiles,websockets,wincertstore,xgboost,numpy,scikitlearn





ModuleNotFoundError: No module named 'PyYAML'